### ISSUE TITLE
[Feature Request] Allow configuring what level of error is displayed

### ISSUE THREAD

**Issue by alsiola** [phindle/error-lens#1]
First of all, thanks for creating this extension!

Can there be a configuration setting for error level shown? My specific case is to disable "Hint" type errors, as shown below, but I can imagine there would be value in a fuller configuration, e.g. `enabledErrorLevels: ["error", "warning"]`

![screen shot 2018-10-10 at 15 52 38](https://user-images.githubusercontent.com/18228137/46745231-91f11980-cca4-11e8-9e68-f1100debf580.png)

Thanks

**Comment by phindle** [comment]
Thank you for the feedback & suggestion Alex. This is a great idea, so I'll implement this as soon as I can.

Stay tuned for updates!

Regards,
Phil

**Comment by phindle** [comment]
Hi Lars.
I will be working on this project this week (hopefully). I am sorry it has taken so long, thank you for your patience, and I hope to have the update out very soon.
Thanks.

**Comment by phindle** [comment]
Implemented in commit 5d67a6fad32cd86cb37e4cc726b580c7a1a84950 ("Implement configuration control over which diagnostics are levelled up.") and a few other subsequent commits.
This enhancement will be rolled out in v1.1.0.

**Comment by phindle** [comment]
Configured via `errorlens.enabledDiagnosticLevels` in the settings.

Default setting is to show all diagnostics, i.e. `errorlens.enabledDiagnosticLevels = [ "error", "warning", "info", "hint" ]`

Example: To show only errors: `errorlens.enabledDiagnosticLevels = [ "error" ]`

**Comment by phindle** [comment]
Now published to Extension Marketplace as v1.1.0.
