### ISSUE TITLE
disable "ErrorLens: No errors or warnings" in status bar

### ISSUE THREAD

**Issue by Yzrsah** [phindle/error-lens#11]
Please provide an option to disable the status bar message when there's no errors.

**Comment by phindle** [comment]
Done, see PR https://github.com/phindle/error-lens/pull/13

**Comment by phindle** [comment]
Will close this when I publish 1.1.0.

**Comment by phindle** [comment]
Now published to Extension Marketplace as v1.1.0.

**Comment by Yzrsah** [comment]
Thank you so much for the update Phil. This is one of the most essential extensions for VSCode. The new setting works well.

**Comment by Yzrsah** [comment]
Thank you so much for the update Phil. This is one of the most essential extensions for VSCode.
The new setting works perfectly.
