### ISSUE TITLE
No longer highlights the entire line

### ISSUE THREAD

**Issue by usernamehw** [phindle/error-lens#15]
Expected:
![screenshot 66](https://user-images.githubusercontent.com/9638156/52729670-a9ca0880-2fca-11e9-9274-a3e4feef9065.png)

Actual:
![screenshot 67](https://user-images.githubusercontent.com/9638156/52729676-afbfe980-2fca-11e9-9fdf-e2997678d420.png)

**Comment by usernamehw** [comment]
I think it was like that from Oct/Nov 2018 in master branch. Still, is this an intentional change?

**Comment by phindle** [comment]
I think I may have fiddled with this a while back.
I'll revert it back but have an option to retain the current (i.e. not the whole line) behaviour.

**Comment by phindle** [comment]
Fixed in commit c201cc3cf2d55f6f43537e908b7d49922602ce70
