### ISSUE TITLE
Updates are too quick

### ISSUE THREAD

**Issue by nealot** [phindle/error-lens#2]
When I'm writing markdown on an empty line, I keep getting a linting warning about trailing-spaces whenever I press 'space'. I think it would be more convenient to only update when the file is saved or maybe after a configurable delay.

**Comment by phindle** [comment]
Thanks for the feedback. This is a great suggestion, so I will implement a configurable delay. I will consider if it's also possible to implement update only on save, but I'll have to work out how that might work. But I see the problem, so I'm sure I can figure out a way to improve this.

**Comment by gersilex** [comment]
Isn't this something that should be done in the problem matcher of VSCode itself? I mean, your (awesome) error-lens is another style to display problems and it shouldn't contain any delay logic, IMHO.
As soon as the code gets those squiggly lines, error-lens should apply its style, too.

Am I missing anything?

**Comment by nealot** [comment]
@gersilex Makes a good point and I would have to agree with him. As I've continued to use the extension, I've come to realize that an artificial delay wouldn't be very beneficial. I'm closing this issue because I don't think it's worth implementing.

**Comment by phindle** [comment]
Thank you for the feedback, it's appreciated!
I am trying to make this configurable and improve it, so hopefully the next release will feature improvements in this area.
