### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kubukoz** [phindle/error-lens#36]
Hi!

I don't see a license in this project, could you add one? As it stands, the project is All Rights Reserved.

Thanks :)

**Comment by maryla-uc** [comment]
Friendly ping. Adding a license file is super easy to do with Github's built in templates, see instructions here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by l-inc** [comment]
@phindle, a friendly reminder here. This is needed by a large number of users waiting for the license due to [the forked repository](https://github.com/usernamehw/vscode-error-lens/issues/46#issuecomment-601197452).

**Comment by phindle** [comment]
Resolved by adding MIT license in this commit:
https://github.com/phindle/error-lens/commit/78bf394de84e6b8c071c07debcf26884833d6412

**Comment by kubukoz** [comment]
Thank you so much!
