### ISSUE TITLE
[Feature Request] Change error text message color

### ISSUE THREAD

**Issue by CarlosRGL** [phindle/error-lens#4]
Great extension! if possible in future updates, change the color of error text and maybe the font size.
keep the great work ;)

**Comment by phindle** [comment]
Thank you! This is a good suggestion, I will try and do this.
Thanks - Phil

**Comment by phindle** [comment]
Improved in 1.1.0. Commit 6da92b55a80f57231eb185cf2bd3b38bc8548674 and others.

**Comment by phindle** [comment]
Now published to Extension Marketplace as v1.1.0.

Issue #7 is still outstanding, this will be implemented in the next release.
