### ISSUE TITLE
Change Error highlight style?

### ISSUE THREAD

**Issue by ianizaguirre** [phindle/error-lens#6]
Is it possible to make the errors look like sublime errors that have a border instead of highlighting the whole line? Reference image can be seen in this post: https://github.com/Microsoft/vscode/issues/9209

**Comment by phindle** [comment]
Yes, that's a good idea. I will add this to the backlog and aim to have this in the 1.1.0 release.

**Comment by ianizaguirre** [comment]
Just letting you know that I figured out a way to do this, using the "Custom CSS Loader" extension. 

So this was my end result:

![vscode-squiggly-error-to-outline-error](https://user-images.githubusercontent.com/29879270/48297096-a3c60800-e46e-11e8-8593-7b2b5b4a0a43.png)

**Comment by phindle** [comment]
I'm not sure how this could be implemented without depending on the CSS Loader extension or somehow hacking the style which VSCode uses for rendering the diagnostics.
If anyone has any ideas, would be good to learn of them.

**Comment by ianizaguirre** [comment]
This is how I did it , maybe it will help you ([Post](https://www.izaguir.re/how-to-make-vscode-error-highlighting-look-more-like-sublime-error-highlighting/)

**Comment by phindle** [comment]
Thanks @ianizaguirre - I had seen your post, it's a neat solution, however, as I mentioned, I think this requires using the CSS loader extension, and it looks like anyone using that extension needs to do some custom setup, so it doesn't seem like something I wanted to use.
