### ISSUE TITLE
Contribute colors instead of settings

### ISSUE THREAD

**Issue by usernamehw** [phindle/error-lens#7]
There is a way to contribute colors in vscode extension:
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescolors

That will allow for users to change colors per theme and hot reload of colors.
You can also set it to theme default color (error/warning - some themes don't use red/orange).

**Comment by Ash258** [comment]
@usernamehw Do you close this on purpose??

I am looking to open issue for hot reload colors, but this issue already contains it, so not sure if I missed something.

![Reload](https://i.imgur.com/F3yyt5g.gif)

**Comment by usernamehw** [comment]
Don't really remember ... I forked it and used color contributions in local version.

**Comment by phindle** [comment]
Hey @usernamehw - how do I access the theme color (e.g. "errorLens.errorColor") via an API? I've added things as a color contribution, but I'm not sure how to get these now.

**Comment by usernamehw** [comment]
@phindle like that:
```typescript
const errorColor = new vscode.ThemeColor("errorLens.errorColor");
```

You should probably create issue in vscode docs if it's not obvious.
