### ISSUE TITLE
Switching tabs removes decorations

### ISSUE THREAD

**Issue by usernamehw** [phindle/error-lens#8]
Issue Type: <b>Bug</b>

![removes_decorations](https://user-images.githubusercontent.com/9638156/47749836-006f3900-dc9f-11e8-8022-281ef0b3d024.gif)

Decorations return after modifying the document. But is it possible to keep them even after switching?

Extension version: 1.0.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by pushqrdx** [comment]
yeah happens here too, makes the extension useless i hope it gets fixed

**Comment by phindle** [comment]
Hi folks - apologies for not getting on to this, I've been busy moving house so I've not been able to look at these issues. As soon as my development PC is back up & running I can sort this out.
Thank you for your patience.

**Comment by phindle** [comment]
Back onto this project at last. Looking at this now.

**Comment by phindle** [comment]
Now published to Extension Marketplace as v1.1.0.
