### ISSUE TITLE
Ability to remove noise from the text

### ISSUE THREAD

**Issue by usernamehw** [phindle/error-lens#9]
Issue Type: <b>Feature Request</b>

Decorations can't be word-wrapped => that makes horizontal space very valuable.
And all 4 types of decorations can be coded by different colors `error`/`warning`/`info`/`hint`.

I would like to have the option to hide all unnecessary words before the actual message, such as:
* **Error:**
* **Warning:**
* **Diagnostic #n of n:**
* **Hint:**
* ...

![not_enough_horizontal_space](https://user-images.githubusercontent.com/9638156/47957166-1f810a00-dfc2-11e8-9a85-3e57d2af3a89.png)

**Comment by phindle** [comment]
Fixed in commit 2a23fc5538369d9adc12eb6000e3380becff4835
